<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'SmartyModule\Module'                                       => __DIR__ . '/Module.php',
    'SmartyModule\Service\SmartyViewResolverFactory'            => __DIR__ . '/src/SmartyModule/Service/SmartyViewResolverFactory.php',
    'SmartyModule\Service\SmartyStrategyFactory'                => __DIR__ . '/src/SmartyModule/Service/SmartyStrategyFactory.php',
    'SmartyModule\Service\SmartyViewTemplateMapResolverFactory' => __DIR__ . '/src/SmartyModule/Service/SmartyViewTemplateMapResolverFactory.php',
    'SmartyModule\Service\SmartyRendererFactory'                => __DIR__ . '/src/SmartyModule/Service/SmartyRendererFactory.php',
    'SmartyModule\Service\SmartyViewTemplatePathStackFactory'   => __DIR__ . '/src/SmartyModule/Service/SmartyViewTemplatePathStackFactory.php',
    'SmartyModule\View\Renderer\SmartyRenderer'                 => __DIR__ . '/src/SmartyModule/View/Renderer/SmartyRenderer.php',
    'SmartyModule\View\Strategy\SmartyStrategy'                 => __DIR__ . '/src/SmartyModule/View/Strategy/SmartyStrategy.php',
);
